#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          claw,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void close_claw(){
	motor[claw] = 30;
	sleep(300);
	motor[claw] = 0;
}

task main()
{
	close_claw();
	int currentDist = SensorValue[Sonar];
	int error = 0;
	int derivative = 0;
	float correction = 0;
	int baseSpeed = 30;
	int targetDist = 50;

	float kp = 1;
	float ki = 0;
	float kd = 0.1;

	int lastError = 0;
	int integral = 0;

	while (true)
	{
		// Read the sensor
		currentDist = SensorValue[Sonar];
		error = targetDist - currentDist;
		integral = error + integral;
		derivative = error + lastError;
		correction = kp*error + ki*integral + kd*derivative;
		motor[right] = baseSpeed - correction;
		motor[left] = baseSpeed + correction;
		lastError = error;
	}
}
